# Generated by Django 3.2 on 2023-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.BigIntegerField()),
                ('log_name', models.TextField()),
                ('log_content', models.TextField()),
            ],
            options={
                'db_table': 'Logs_Content',
            },
        ),
        migrations.CreateModel(
            name='LogsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfy_matrix', models.TextField()),
                ('logs', models.TextField()),
                ('marked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Logs_Info',
            },
        ),
        migrations.CreateModel(
            name='SystemsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOSTNAME', models.CharField(max_length=255)),
                ('INTERFACE', models.CharField(max_length=255)),
                ('SERVER_TYPE', models.CharField(max_length=255)),
                ('SERVER', models.CharField(max_length=255)),
                ('BIOS', models.CharField(max_length=255)),
                ('CPU', models.TextField()),
                ('MEMORY', models.CharField(max_length=255)),
                ('HCA', models.CharField(max_length=255)),
                ('HCA_FW', models.CharField(max_length=255)),
                ('KERNEL', models.CharField(max_length=255)),
                ('ILOM', models.CharField(max_length=255)),
                ('IMAGE', models.CharField(max_length=255)),
                ('OS', models.CharField(max_length=255)),
                ('INTERFACE_INFO', models.TextField()),
            ],
            options={
                'db_table': 'Systems_Info',
            },
        ),
        migrations.CreateModel(
            name='TasksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_category', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('task_system', models.CharField(max_length=1000)),
                ('perfy_matrix', models.CharField(max_length=1000)),
                ('html_template', models.CharField(max_length=1000)),
                ('index_columns', models.TextField()),
                ('best_values', models.TextField()),
                ('post_user', models.TextField()),
            ],
            options={
                'db_table': 'Tasks_Info',
            },
        ),
    ]
