# Generated by Django 3.2 on 2023-07-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OHD_Perfy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsinfo',
            name='marked',
        ),
    ]
