# Generated by Django 3.2 on 2023-07-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHD_Perfy', '0002_remove_logsinfo_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsinfo',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
