# Generated by Django 3.2 on 2023-07-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHD_Perfy', '0003_logsinfo_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('post_user', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
